spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.130:8848
        password: nacos
        username: nacos
        namespace: third
    alicloud:
      access-key: LTAI5tSMQjRn2aWaXWYYezqU
      secret-key: 4RTcGMYo6UGNGAlvoicr4bVgw3ysWH
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

  application:
    name: mall-third-party





mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      #不删除
      logic-not-delete-value: 1
      #删除


server:
  port: 10200



logging:
  level:
    com.katzenyasax.mall: debug



alibaba:
  cloud:
    access-key: LTAI5tSMQjRn2aWaXWYYezqU
    secret-key: 4RTcGMYo6UGNGAlvoicr4bVgw3ysWH
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket: katzenyasax-mall







